apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immich.fullname" . }}-machine-learning
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: machine-learning
spec:
  replicas: {{ .Values.machinelearning.replicaCount }}
  selector:
    matchLabels:
      {{- include "immich.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: machine-learning
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.web.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "immich.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: machine-learning
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "immich.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.machinelearning.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-machinelearning
          securityContext:
            {{- toYaml .Values.machinelearning.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}/immich-machine-learning:{{ include "immich.tag" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "immich.fullname" . }}
            - secretRef:
                name: {{ include "immich.fullname" . }}
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          startupProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.machinelearning.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ include "immich.dataMountPath" . }}
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /cache
              {{- if .Values.machinelearning.persistence.subPath }}
              subPath: {{ .Values.machinelearning.persistence.subPath }}
              {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "immich.fullname" .) .Values.machinelearning.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp
          emptyDir: {}
        - name: cache
          {{- if .Values.machinelearning.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-machine-learning" (include "immich.fullname" .)) .Values.machinelearning.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.machinelearning.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.machinelearning.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.machinelearning.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
