---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.fullname" . }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
data:
  {{- $postgresHost := include "immich.postgresql.host" . }}
  {{- $postgresPort := include "immich.postgresql.port" . }}
  {{- $postgresDB   := include "immich.postgresql.database" . }}
  {{- $postgresUser := include "immich.postgresql.username" . }}
  {{- $postgresPass := include "immich.postgresql.password" . }}
  {{- $postgresSSLMode := include "immich.postgresql.sslmode" . }}
  DB_HOSTNAME: {{ $postgresHost | b64enc | quote }}
  DB_PORT: {{ $postgresPort | b64enc | quote }}
  DB_DATABASE_NAME: {{ $postgresDB | b64enc | quote }}
  DB_USERNAME: {{ $postgresUser | b64enc | quote }}
  {{- if and $postgresPass (not .Values.postgresql.existingSecret) }}
  DB_PASSWORD: {{ $postgresPass | b64enc | quote }}
  {{- else }}
  DB_PASSWORD: {{ print "@@POSTGRES_PASSWORD@@" | b64enc | quote }}
  {{- end }}


  {{- $redisHost := include "immich.redis.host" . }}
  {{- $redisPort := include "immich.redis.port" . }}
  {{- $redisUser := include "immich.redis.username" . }}
  {{- $redisPass := include "immich.redis.password" . }}
  {{- $redisDb := include "immich.redis.db" . }}
  REDIS_HOSTNAME: {{ $redisHost | b64enc | quote }}
  REDIS_PORT: {{ $redisPort | b64enc | quote }}
  REDIS_DBINDEX: {{ $redisDb | b64enc | quote }}
  REDIS_USERNAME: {{ $redisUser | b64enc | quote  }}
  {{- if and $redisPass (not .Values.redis.auth.existingSecret) }}
  REDIS_PASSWORD: {{ $redisPass | b64enc | quote }}
  {{- else }}
  REDIS_PASSWORD: {{print "@@REDIS_PASSWORD@@" | b64enc | quote }}
  {{- end }}

