---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.fullname" . }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
stringData:
  {{- $postgresHost := include "immich.postgresql.host" . }}
  {{- $postgresPort := include "immich.postgresql.port" . }}
  {{- $postgresDB   := include "immich.postgresql.database" . }}
  {{- $postgresUser := include "immich.postgresql.username" . }}
  {{- $postgresPass := include "immich.postgresql.password" . }}
  {{- $postgresSSLMode := include "immich.postgresql.sslmode" . }}
  DB_HOSTNAME: {{ $postgresHost | quote }}
  DB_PORT: {{ $postgresPort | quote }}
  DB_DATABASE_NAME: {{ $postgresDB | quote }} 
  DB_USERNAME: {{ $postgresUser | quote }}
  {{- if and $postgresPass (not .Values.postgresql.existingSecret) }}
  DB_PASSWORD: {{ $postgresPass | quote }}
  {{- else }}
  DB_PASSWORD: "@@POSTGRES_PASSWORD@@"
  {{- end }}


  {{- $redisHost := include "immich.redis.host" . }}
  {{- $redisPort := include "immich.redis.port" . }}
  {{- $redisUser := include "immich.redis.username" . }}
  {{- $redisPass := include "immich.redis.password" . }}
  {{- $redisDb := include "immich.redis.db" . }}
  REDIS_HOSTNAME: {{ $redisHost | quote }}
  REDIS_PORT: {{ $redisPort | quote }}
  REDIS_DBINDEX: {{ $redisDb | quote }} 
  REDIS_USERNAME: {{ $redisUser | quote  }}
  {{- if and $redisPass (not .Values.redis.auth.existingSecret) }}
  REDIS_PASSWORD: {{ $redisPass | quote }}
  {{- else }}
  REDIS_PASSWORD: "@@REDIS_PASSWORD@@"
  {{- end }}

  {{- $typesenseHost := include "immich.typesense.host" . }}
  {{- $typesensePort := include "immich.typesense.port" . }}
  {{- $typesenseProtocol := include "immich.typesense.protocol" . }}
  {{- $typesenseApiKey := include "immich.typesense.apkKey" . }}
  TYPESENSE_HOST: {{ $typesenseHost | quote }}
  TYPESENSE_PORT: {{ $typesensePort | quote }}
  TYPESENSE_PROTOCOL: {{ $typesenseProtocol | quote  }}
  TYPESENSE_API_KEY: {{ $typesenseApiKey }}

