apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich.fullname" . }}-machine-learning
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: machine-learning
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3003
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "immich.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: machine-learning
