{{- if and .Values.ssl.enabled (not .Values.ssl.existingSecret ) -}}
{{- if .Values.ssl.domains }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "lldap.fullname" . }}-ldaps-tls
spec:
  secretName: {{ template "lldap.fullname" . }}-ldaps-tls
  issuerRef:
    name: {{ default "letsencrypt-staging" .Values.ssl.issuer.name }}
    kind: {{ default "ClusterIssuer" .Values.ssl.issuer.kind }}
  dnsNames:
  {{- range .Values.ssl.domains }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
