---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    {{- include "dockermailserver.labels" . | nindent 4 }}
  name: {{ template "dockermailserver.fullname" . }}-custom-configs
data:
  {{- include "dockermailserver.custom-configs" . | nindent 2 }}
