{{- if .Values.gendkim.job.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dockermailserver.fullname" . }}-scripts
  labels:
    {{- include "dockermailserver.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded
data:
{{ (.Files.Glob "scripts/*.sh").AsConfig | indent 2 }}
{{- end }}
