---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    {{- include "dockermailserver.labels" . | nindent 4 }}
  name: {{ template "dockermailserver.fullname" . }}-configs
data:
  postfix-main.cf: |
    mydestination = localhost.$mydomain, localhost
  {{/* Enable proxy protocol for postscreen / dovecot */}}
  {{- if or .Values.haproxy.enabled .Values.proxyProtocol.enabled }}  # Necessary to permit proxy protocol from haproxy to postscreen
    postscreen_upstream_proxy_protocol = haproxy
  {{- end }}
  {{- if not .Values.spfTestsDisabled }}
    smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org, reject_rbl_client bl.spamcop.net{{ range .Values.rblRejectDomains }}, reject_rbl_client {{ . }}{{ end }}
  {{- end }}

  postfix-master.cf: |
  {{- if index .Values.extraConfigFiles "postfix-master.cf" }}
    {{- get .Values.extraConfigFiles "postfix-master.cf" | nindent 4 }}
  {{- end }}
    # Necessary to permit proxy protocol from haproxy to smtpd
  {{- if or .Values.haproxy.enabled .Values.proxyProtocol.enabled }}
    submission/inet/smtpd_upstream_proxy_protocol=haproxy
    submissions/inet/smtpd_upstream_proxy_protocol=haproxy
  {{- end }}

  dovecot-services.conf: |
  {{- if or .Values.haproxy.enabled .Values.proxyProtocol.enabled }}
    haproxy_trusted_networks = {{ .Values.proxyProtocol.trustedNetworks }}
  {{ end }}
    service imap-login {
      inet_listener imap {
      {{- if or .Values.haproxy.enabled .Values.proxyProtocol.enabled }}
        haproxy = yes
        port = 10143
      {{- end }}
      {{- if or .Values.ssl.enabled }}
        ssl = yes
      {{- end }}
      }
      inet_listener imaps {
      {{- if or .Values.haproxy.enabled .Values.proxyProtocol.enabled }}
        haproxy = yes
        port = 10993
      {{- end }}
        ssl = yes
      }
    }
    service pop3-login {
      inet_listener pop3 {
      {{- if or .Values.haproxy.enabled .Values.proxyProtocol.enabled }}
        haproxy = yes
        port = 10110
      {{- end }}
      {{- if or .Values.ssl.enabled }}
        ssl = yes
      {{- end }}
      }
      inet_listener pop3s {
      {{- if or .Values.haproxy.enabled .Values.proxyProtocol.enabled }}
        haproxy = yes
        port = 10995
      {{- end }}
        ssl = yes
      }
    }

  {{- (.Files.Get "config/fail2ban-*.cf") | nindent 2 }}

  {{/* https://doc.dovecot.org/configuration_manual/replication/ */}}
  10-replication.conf: |
    mail_plugins = $mail_plugins notify replication

  80-replication.conf: |
    service replicator {
      process_min_avail = 1
      unix_listener replicator-doveadm {
        mode = 0600
        user = docker
      }
    }

    service aggregator {
      fifo_listener replication-notify-fifo {
        user = docker
      }
      unix_listener replication-notify {
        user = docker
      }
    }
    
    doveadm_port = 4711
    {{/* TODO: change default password */}}
    doveadm_password = secret

    service doveadm {
      inet_listener {
        port = 4711
        {{- if .Values.ssl.enabled }}
        ssl = yes
        {{- end }}
      }
    }

    plugin {
      {{- $name := include "dockermailserver.fullname" . }}
      {{- range $index := until (int .Values.dockermailserver.replicas) }}
      mail_replica = tcp:{{ $name }}-{{ $index }}.{{ $name }}-headless
      {{- end }}
    }

  91-override-sieve.conf: |
    plugin {
      sieve = /var/mail/sieve/%d/%n/.dovecot.sieve
      sieve_dir = /var/mail/sieve/%d/%n/sieve
    }

  dkim_signing.conf: |
    # documentation: https://rspamd.com/doc/modules/dkim_signing.html

    enabled = true;

    sign_authenticated = true;
    sign_local = true;

    use_domain = "header";
    use_redis = false;   # don't change unless Redis also provides the DKIM keys
    use_esld = true;

    check_pubkey = true; # you wan't to use this in the beginning

    domain {
      {{- range $domain := .Values.domains }}
      {{- $path := printf "/tmp/docker-mailserver/dkimkeys/%s/mail.private" . }}
      {{ $domain }} {
        path = {{ $path }};
        selector = "mail";
      }
    {{- end }}
    }

  am-i-healthy.sh: |
    #!/bin/bash
    # this script is intended to be used by periodic kubernetes liveness probes to ensure that the container
    # (and all its dependent services) is healthy
    {{ range .Values.livenessTests.commands -}}
    {{ . }} && \
    {{- end }}
    echo "All healthy"
