{{/* This whole template is only necessary if we're using rainloop */}}
{{ if .Values.rainloop.enabled -}}  
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    {{- include "dockermailserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: rainloop
  name: {{ template "dockermailserver.fullname" . }}-rainloop
spec:
  replicas: {{ .Values.rainloop.replicas }}
  selector:
    matchLabels:
      {{- include "dockermailserver.labels" . | nindent 6 }}
      app.kubernetes.io/component: rainloop
  strategy: {{- toYaml .Values.rainloop.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "dockermailserver.labels" . | nindent 8 }}
        app.kubernetes.io/component: rainloop
      {{- if .Values.rainloop.annotations }}
      annotations:
        {{ toYaml .Values.rainloop.annotations | nindent 8 }}  
      {{ end }}          
    spec:
      serviceAccountName: {{ template "dockermailserver.rainloop.serviceAccountName" . }}
      containers:
        - name: rainloop
          image: "{{ .Values.rainloop.image.name }}:{{ .Values.rainloop.image.tag }}"
          imagePullPolicy: {{ .Values.rainloop.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: data
              mountPath: "/rainloop/data"
              subPath: "rainloop"
          env:
          - name: LOG_TO_STDOUT
            value: "true"
      volumes:
      - name: "data"
        persistentVolumeClaim:
          claimName: {{ template "dockermailserver.fullname" . }}-rainloop
{{- end }}

