{{- if not .Values.persistent.existingClaim -}}
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ template "dockermailserver.fullname" . }}
  annotations:
  {{- if .Values.persistent.annotations }}
  {{ toYaml .Values.persistent.annotations | indent 2 }}
  {{ end }}
  labels:
    {{- include "dockermailserver.labels" . | nindent 4 }}
  {{- if .Values.persistent.storageClass }}
    storageClassName: {{ .Values.persistent.storageClass }}
  {{- end }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistent.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistent.size | quote }}
  {{- if .Values.persistent.selector }}
  selector:
{{ toYaml .Values.persistent.selector | indent 4 }}
  {{ end }}
{{- end }}
