{{- if and .Values.roundcube.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "dockermailserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: roundcube
  name: {{ template "dockermailserver.roundcube.serviceAccountName" . }}
{{- end -}}
