{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "dockermailserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: dockermailserver
  name: {{ template "dockermailserver.serviceAccountName" . }}
{{- end -}}
