{{- if and .Values.rainloop.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "dockermailserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: rainloop
  name: {{ template "dockermailserver.rainloop.serviceAccountName" . }}
{{- end -}}
