{{/* Append the hardcoded settings */}}
{{- define "coredns-id.harcodedValues" -}}

ingress: {}

persistence:
  config:
    enabled: true
    type: configMap
    name: {{ include "bjw-s.common.lib.chart.names.fullname" $ }}-corefile
    mountPath: /etc/coredns
    readOnly: true


{{- end -}}
{{- $_ := merge .Values (include "coredns-id.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
