apiVersion: v2
name: immich
description: Self-hosted photo and video backup solution directly from your mobile phone.
type: application
home: https://immich.app/
sources:
  - https://github.com/pcmid/charts
  - https://github.com/immich-app/immich
version: 0.1.0
appVersion: 1.78.1
kubeVersion: ">=1.22.0-0"
keywords:
  - immich
  - photo
  - video
  - backup

dependencies:
  - name: postgresql
    version: '^12'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: '^18'
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: typesense
    version: '>=0'
    repository: https://charts.shabi.id/
    condition: typesense.enabled

