#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- Image repository
  repository: ghcr.io/pcmid/coredns-id
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: v1.10.1-id.20230501080147

args: ["-conf", "/etc/coredns/Corefile"]

env:
  # -- Set the container timezone
  TZ: UTC

controller:
  strategy: RollingUpdate

service:
  # -- Configures settings for the DNS service.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: true
    ports:
      http:
        enabled: false
      dns:
        enabled: true
        port: 53
        protocol: UDP

Corefile: |
  . {
    errors
    log
    health
    ready

    blocklist https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt

    # ads not build
    #ads {
    #  default-lists
    #  log
    #  auto-update-interval 24h
    #  list-store ads-cache
    #}

    dispatch https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf {
      maxfails 3
      to 114.114.114.114 223.5.5.5 119.29.29.29
      # reload 24h # unimplement
    }

    forward . /etc/resolv.conf

    cache 1024
    loop
    reload
    loadbalance
  }

